version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.0
    ports:
    - 19200:9200
    - 19300:9300
    environment:
    - discovery.type=single-node
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
volumes:
  esdata:
    driver: local